#include "block.h"
#include "sha256.h"
#include <sstream>
#include <iomanip>

using namespace std;

Block::Block() : nonce(0), timestamp(0), waitTime(0) {}

Block::Block(const string& prevHash, const vector<Transaction>& txs) {
    parentHash = prevHash;
    nonce = 1000 + rand() % 9000;
    waitTime = 0;
    difficulty = string(1, '0');
    timestamp = time(nullptr);
    transactions = txs;
    merkleRoot = calculateMerkleRoot(transactions);
    hash = calculateHash();
}

Block::Block(const string& prevHash, const vector<Transaction>& txs, int wait) {
    parentHash = prevHash;
    waitTime = wait;
    nonce = 0;
    difficulty = "PoET"; // Indicates PoET consensus
    timestamp = time(nullptr);
    transactions = txs;
    merkleRoot = calculateMerkleRoot(transactions);
    // In a real implementation, the waitCertificate would be generated by TEE
    stringstream ss;
    ss << "WAIT_" << wait << "_" << timestamp;
    waitCertificate = sha256(ss.str());
    hash = calculateHash();
}

string Block::calculateHash() const {
    stringstream ss;
    ss << parentHash << nonce << difficulty << timestamp << merkleRoot << waitCertificate << waitTime;
    return sha256(ss.str());
}

string Block::calculateMerkleRoot(const vector<Transaction>& transactions) {
    if (transactions.empty())
        return "";

    string combinedHash;
    for (const auto& tx : transactions) {
        stringstream txStream;
        txStream << tx.sender << tx.receiver << tx.amount;
        combinedHash += sha256(txStream.str());
    }

    return sha256(combinedHash);
}